_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 8
    BATCH_SIZE_PER_IMAGE: 128
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('my_dataset',)
  TEST: ('',)
DATALOADER:
  NUM_WORKERS: 1
SOLVER:
  STEPS: (12000, 16000)
  BASE_LR: 0.0002
  IMS_PER_BATCH: 2
  MAX_ITER: 90000
  WARMUP_ITERS: 100
