_BASE_: "../Base-RCNN-VGG.yaml"
MODEL:
  MASK_ON: False
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 8
  BACKBONE:
    FREEZE_AT: 2
DATASETS:
  TRAIN: ("my_datasets",)
  TEST: ()
DATALOADER:
  NUM_WORKERS: 1
SOLVER:
  STEPS: (12000, 16000)
  IMS_PER_BATCH: 2
  BASE_LR: 0.0002
  MAX_ITER: 90000

